# fly.toml file generated for purple-forest-9586 on 2023-04-07T18:11:04+03:00

app = "purple-forest-9586"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "arn"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
